package com.example.inventorymanagmentsystem.models;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * Model for a single inventory item. I use this as the Room entity for the "item" table so each row
 * has id, name, category (ItemType), description and quantity.
 */
@Entity(tableName = "item")
public class Item {
    @PrimaryKey(autoGenerate = true)
    private int id;
    @ColumnInfo(name = "name")
    private String name;
    @ColumnInfo(name = "item_type")
    private ItemType type;
    @ColumnInfo(name = "description")
    private String description;

    @ColumnInfo(name = "quantity")
    private int currentQuantity; // I keep the field name in camelCase so Room can match it with my constructor params

    public Item(int id, String name, ItemType type, int currentQuantity, String description) {
        // This is the constructor Room will use because it has all the columns, so I keep the parameter names consistent with the fields
        this.id = id;
        this.name = name;
        this.type = type;
        this.currentQuantity = currentQuantity;
        this.description = description;
    }

    public Item() {
    }

    @Ignore
    public Item(String name, ItemType type, int currentQuantity, String description) {
        // I use this constructor when I create a new item from the UI (id will be autogenerated)
        this.name = name;
        this.type = type;
        this.currentQuantity = currentQuantity;
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getCurrentQuantity() {
        return currentQuantity;
    }

    public void setCurrentQuantity(int currentQuantity) {
        // I expose the quantity through this setter so I can update stock when I need it
        this.currentQuantity = currentQuantity;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ItemType getType() {
        return type;
    }

    public void setType(ItemType type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
